# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 19:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='nombre',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Noticia'),
        ),
    ]
