# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del usuario')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo de servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Tipo_Servicio'),
        ),
    ]
