# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del servicio'),
        ),
    ]
