# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 19:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_auto_20180606_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nombre del servicio'),
        ),
        migrations.AlterField(
            model_name='tipo_servicio',
            name='tipo',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Tipo de servicio'),
        ),
    ]
