# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 18:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20180606_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('^[0-9]+$', 'No se permiten espacios en blanco ni letras, solo se permiten numeros,')], verbose_name='Telefono'),
        ),
    ]
